---
- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present

- name: Install Python MySQL dependencies
  apt:
    name: python3-pymysql
    state: present

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Menunggu MariaDB Untuk Siap
  wait_for:
    port: 3306
    delay: 5
    timeout: 30

- name: Check Jika Root Password Sudah Di Set
  shell: |
    sudo mysql -u root -e "SELECT 1;" >/dev/null 2>&1
    echo $?
  register: root_access_check
  changed_when: false

- name: Set Root Password Jika Belum Di Set (Menggunakan mysqladmin)
  command: >
    mysqladmin -u root password "admin123"
  when: root_access_check.stdout == "0"

- name: Create .my.cnf for root access
  copy:
    content: |
      [client]
      user=root
      password=admin123
    dest: /root/.my.cnf
    mode: 0600

- name: Set root password untuk all hosts
  mysql_user:
    name: root
    password: "admin123"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
    state: present
  loop:
    - "localhost"
    - "127.0.0.1"
    - "::1"

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove remote root users
  mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
  loop:
    - "%"
    - "::1"

- name: Create Nextcloud database
  mysql_db:
    name: nextcloud
    state: present

- name: Create Nextcloud user
  mysql_user:
    name: admin
    password: admin123
    priv: "nextcloud.*:ALL"
    host: '%'
    state: present

- name: Configure MariaDB to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mariadb

- name: Flush privileges
  mysql_query:
    query: "FLUSH PRIVILEGES"

- name: Restart MariaDB to apply changes
  service:
    name: mariadb
    state: restarted
